name: 'Create Pull Request'
description: 'Automated creation of Pull Request'
inputs:
  github-token:
    description: 'token for github'
    required: true
  head-branch:
    description: 'branch to merge into base branch'
    required: true
    default: 'production'
  base-branch:
    description: 'base branch to merge into'
    required: true
    default: 'development'
  pull-request-title:
    description: 'title for Pull Request'
    default: 'Generated Pull Request'
  pull-request-body:
    description: 'Body for Pull Request'
    default: ':crown:'
  label-name:
    description: 'label to filter'
    default: 'automerge'
runs:
  using: 'node12'
  main: 'dist/index.js'
