name: 'Create Pull Request'
description: 'Automated creation of Pull Request'
inputs:
  github-token:  # id of input
    description: 'token for github'
    required: true
  head-branch:
    description: 'branch to merge into base branch'
    required: true
    default: 'production'
  base-branch:
    description: 'base branch to merge into'
    required: true
    default: 'development'
  label-name:
    description: 'label to filter'
    default: 'automerge'
outputs:
  message:
    description: 'output message'
runs:
  using: 'node12'
  main: 'dist/index.js'
